### ISSUE TITLE
FSF Al Rayak - v.002

### ISSUE THREAD

**Issue by chrisleaptrott** [CntoDev/cnto-mmt-repo#12]
http://www.armaholic.com/page.php?id=28564

I've made a post about this terrain before and have already done some testing of it. Looks and areas aside, it seems to be VERY solid and I would like to test it further for compatibility on the server. I feel it would make a nice addition to our maps and its quite small compared to other maps of the same size.

**Comment by CNTODachi** [comment]
We have had CUP now for a while I know we shouldn't add this to the next repo update, but for the repo update scheduled for May can we add?
