### ISSUE TITLE
ACE3 Advanced Medical System

### ISSUE THREAD

**Issue by ghost** [CntoDev/cnto-mmt-repo#2]
Following a test of the ace3mod's AMS, I have uploaded a video of a small post-mission consensus from all the members who attended.

[![Click to View](http://img.youtube.com/vi/qWKVWUnnnKg/0.jpg)](http://www.youtube.com/watch?v=qWKVWUnnnKg)

**Comment by CNTODachi** [comment]
I know this subject isn't quite dead but I would like to get it going again so assigning myself. I will post the exact settings I will use for testing and possible dates for those tests.

Also seeing as my new training template has the new medical training area might I suggest that I create various different versions with advanced enabled with different settings and advanced enabled along with revive module and we as devlopment members test ourselves to see which feels right and then set up a mini op or even better a training with these settings enabled?

**Comment by freghar** [comment]
This issue was moved to CntoDev/mods#3
