### ISSUE TITLE
Fast Rope Script

### ISSUE THREAD

**Issue by chrisleaptrott** [CntoDev/cnto-mmt-repo#52]
I've got a working Fast Rope script to hold us over until the Ace3 guys get around to re-implementing it. I've got it set up and working for all 'appropriate' helicopters: Blackhawks, MELB Littlebirds, and the Chinook. It works for the vanilla choppers too.

I've done minor tests of it and the only thing I'd like to see better about it is the animation, but that's nothing major. It gets the job done perfectly well. I am also looking into the option of only the pilot being able to initiate the ropes.

If approved, I'll add it to the mission templates.

**Comment by CNTODachi** [comment]
With ACE3 finally introducing Fast roping can I please suggest this topic is closed and we conduct testing of ACE3 Fast roping instead of implementing this in #88

**Comment by milivojm** [comment]
Ok. I will enable this in the template if you want.

http://ace3mod.com/wiki/feature/fastroping.html

**Comment by freghar** [comment]
This feature didn't work out well, neither me nor @CNTODachi were able to enter mission lobby on a dedicated server when it was enabled, so the final version of r0b10 will be without it.

I'm keeping this issue open for future testing & enablement.
