### ISSUE TITLE
ALIVE testing

### ISSUE THREAD

**Issue by chrisleaptrott** [CntoDev/cnto-mmt-repo#73]
This will be the spot for adding data relating to ALIVE testing.

http://alivemod.com/

ALiVE is a mission automation mod with a number of features. This mod is being proposed as a potential 'effort-saver' for our MMT. Please post any testing notes you have here. Discussion about this mod and DAC can be had on the following thread on the CNTO forums:

http://www.carpenoctem.co/forums/m/26081621/viewthread/25630311-thoughts-on-dac-alive/page/1/post/111869772

**Comment by freghar** [comment]
This issue was moved to CntoDev/mods#6
