### ISSUE TITLE
DAC Testing

### ISSUE THREAD

**Issue by chrisleaptrott** [CntoDev/cnto-mmt-repo#74]
http://www.armaholic.com/page.php?id=25550

This is for the collection of any data relating to testing DAC.

Further discussion can be held on the ALIVE/DAC forum on the main CNTO forums.

http://www.carpenoctem.co/forums/m/26081621/viewthread/25630311-thoughts-on-dac-alive/page/1/post/111869772

**Comment by freghar** [comment]
This issue was moved to CntoDev/mods#7
