### ISSUE TITLE
CUP testing

### ISSUE THREAD

**Issue by chrisleaptrott** [CntoDev/cnto-mmt-repo#82]
CUP's latest update has shown a very 'near-to-completion' representation of the MOD. Its up to a standard that I think is very usable by us for missions. Given other changes and things going on, I've set this to low priority at the moment, feel free to change that if this is something we need to advance on faster.

Just to list a few of the major considerations:
Replaces and consolidates mods like RHS, LOP, and several weapons packs (HLC and such).
It is already compatible with ACE via its own clean-up mod addition.
Offers a TON of additional units and factions compared to RHS and LOP combined.
All the stuff is being made vanilla compatible first and foremost. None of this HP errors by LOP causing crashes.
A HUGE team of very dedicated developers and a lot of community support. Lots of things have been donated from around all of the Arma 3 community.

I am going to test this in my free time to see what bugs and things I can find. I'll post my findings soon.

**Comment by CNTODachi** [comment]
Any update on this? It is still listed as High Priority and been a Month since last comment taking a look CUP back log of issues think we should maybe bump this down to low priority.
