### ISSUE TITLE
LOP Crashes

### ISSUE THREAD

**Issue by chrisleaptrott** [CntoDev/cnto-mmt-repo#84]
A lot of communities are already dropping LOP and going to things like CAF. I know we used CAF prior to LOP....and its not ideal, but its also not crashing us. That's one possible solution, there could be others while we wait for CUP.

I'd say we just drop LOP for the time being, even if we don't replace it immediately. This will prevent us from even the risk of it causing a crash.

**Comment by CNTODachi** [comment]
LOP received an update to 1.8 and therefore seems to be fine. Suggest we add the label Mod Update and close the issue.
