### ISSUE TITLE
Upgrading the template - r0b10

### ISSUE THREAD

**Issue by milivojm** [CntoDev/cnto-mmt-repo#88]
Template r0b9 needs to be upgraded to adapt to upgrades in the CNTO modset. The list of mods is provided in CNTO R&D Google Drive folder.

**Comment by milivojm** [comment]
I have downloaded the required modset, migrated the r0b9 to Eden and successfully opened it. However, there are some serious issues listed here which I'll try to fix.

1. The biggest issue is performance. Running a template in preview mode causes stuttering every second. I've tried to remove assets one by one and found that certain weapon class might be causing this. Removing the weapons from all 107 template soldiers will not produce this problem. This issue is a must fix for me.
1. There is a minor issue with message popping up while opening the editor. One is related to LOP and the other one to CUP terrains. As these are mod related issues, we can't fix them. 
1. Report file reports some BLUFOR soldiers have too much gear even if the gear itself is not removed from the inventory. Still, I'd like as clean report log file as I can get and will try to fix it. 

Point 1 is a deal breaker because we can't expect mission makers wasting time on low performance mission.

Question for all involved - should I remove the non-unit, non-vehicle empty objects being deployed in the mission as 'reference objects'? There is a ton of houses, walls, etc used for reference. The general idea behind it was to drag & drop them around the map when building structures and defense. But, with new EDEN features, ability to search assets, I don't think that's required any more.

**Comment by Abuk007** [comment]
1. Is the performance/weapon problem consistent? Can anyone else confirm this too?
2. LOP and CUP messages were mentioned in issue #84 .

Regarding reference objects (structures) - I do believe we dont need them anymore with eden. They don't have any special parameters and they take up some performance on template so ditching them should not harm us in any way.

**Comment by CNTODachi** [comment]
Reference Structures:

I've never used them even before Eden and now with the search function they are redundant get rid of them in my opinion.

Reference Weapons/performance issue:

Can I ask what the weapon in question was that you removed to correct the issue?

**Comment by milivojm** [comment]
Hey,

I wasn't able to pinpoint the exact weapon class. What I did is 

1. started the preview of the template
1. verify that the stuttering problem exists
1. hit escape and in debug window executed a code that remove the weapons from all units
1. continued the mission and stuttering was gone

The plan now is to remove weapon, one by one and see which one is doing this.

**Comment by JamesTheClarke** [comment]
> The biggest issue is performance. Running a template in preview mode causes stuttering every second. I've tried to remove assets one by one and found that certain weapon class might be causing this. Removing the weapons from all 107 template soldiers will not produce this problem. This issue is a must fix for me.

> Is the performance/weapon problem consistent? Can anyone else confirm this too?

This has always been an issue with the template if all playable soldiers are previewed at once. Most likely candidate are high polygon weapons such as the HLC M249 (which is used by RHS as default BluFor AR) but the TF47 AT4 launchers are also likely culprits.

To be clear, the performance issue only really comes into significant play when previewing the entire template, not in MP missions / events as there are only going to be those soldiers present, which are controlled by a player as we disable AI in the selection screen.

If a mission maker is experiencing performance issue to a crippling degree in preview mode one can load the same map with only one active soldier and then create the MCC mission via "save/load to profile" function. Friendly assets (soldiers, base, vehicles) are usually not spawned by the GM, only enemy assets - and those are map, not template dependent.

**Comment by milivojm** [comment]
Ok Clarke, thanks for that, I didn't know this was occurring regularly in template missions. I will still try to find the culprit, if nothing just for curiosity.

**Comment by JamesTheClarke** [comment]
One of the best fixes for the situation will be a complete switch to CUP as they employ the strictest (lowest) budget of polygons per asset of all overhaul mods. The question is: is it acceptable to switch now, but endure the odd graphical artefact errors as reported on our forums or should we keep waiting for a further, more polished CUP update. Both carries a lot of pros and cons, it's a tough sale either way. In any case the CUP test template I've created a while back would be ready to go with complete BluFor loadouts balanced out for CUP and 4 men FT structure.

**Comment by milivojm** [comment]
I don't have a preference for or against CUP, my personal bias stops with 'are the bullets flying on the other side of the barrel' and 'does it break the server'. If both conditions are satisfied, I'm ok with it. :)

NCOs, just to be on the same page - planned mod set roll-out is this weekend, right? I think I'll be able to clear some of these things by then seeing that Clarke said some of them are really not issues at all.

**Comment by TRyujin** [comment]
We update the template on Saturdays. If the template is ready for this Saturday, we'll do it then, if not we'll do it on next one. Server side (both) we're ready for the update, we're waiting for template only so MM can update their missions and create new ones.

For now it's best we don't touch too many stuff, so besides props nothing else for now. We'll have two months worth of time to test and retest various different settings. Feed the pigs, we'll roll in mud with them later.

**Comment by JamesTheClarke** [comment]
> Feed the pigs, we'll roll in mud with them later.

Never heard that one before, but I gotta say: I'm loving it. xD

**Comment by milivojm** [comment]
Pigs are dirty and the farmer is in the mud up to his knees. :)

Ok, I've started the mission on local dedicated server, seems working. Log files are filled with LOP, RHS, MELB errors - so I've attached them here:

https://drive.google.com/file/d/0B8T9N5ODuzJgMXNZMHpSNkdOM1k/view?usp=sharing

MCC is working (despite giving a script error in the log)

@freghar - can we do a test run this week on your dedicated server, let's say Thursday 22h CET? Just template test, nothing else.

**Comment by Abuk007** [comment]
We're sticking to LOP and RHS for the time being until we can prove that they are causing major issues such as server crashes. They both have been updated and errors poping up are mostly unaffecting us. CUP still needs months before it gets to a polished state. 

So as Dachi, Ryujin and I concluded in this topic: we stick to the plan - get everything prepped (modules, removing structures etc), eliminate game-breaking things (if there are any) and release the template alongside repo update.

Then we continue with refining, slimming and optimizing template and eventual additions or removals.

Also we should be aware of upcoming arma update - 1.58 - in case it breaks our template/modset entirely - but that's another topic and we can't predict exact date or results.

**Comment by milivojm** [comment]
Should I report the errors to mod developers?

**Comment by Abuk007** [comment]
It's not necessary but if you have time and will that can be beneficial for us in the future.

**Comment by CNTODachi** [comment]
I can conduct testing on the server all day tomorrow Thursday if we can get the server correctly configured tonight or in the morning at some point. Also the template uploaded.

That way we can give it the go ahead for release on Saturday with the new repo.

What do you guys think?

**Comment by milivojm** [comment]
.pbo is uploaded on my Google Drive => https://drive.google.com/file/d/0B8T9N5ODuzJgLXpMb2YyTWJjM1E/view?usp=sharing

**Comment by freghar** [comment]
@CNTODachi - uff, I just discovered this discussion (3AM). I may be able to get all the required mods in the morning and start up my server, but no promises.

**Comment by milivojm** [comment]
_Template test cases_

- [ ] Playable slots are correct
- [ ] Units load with the right gear
- [ ] Vehicles have the right gear
- [ ] Ammo boxes and other weapon caches are correctly loaded
- [ ] All vehicles can be driven and can fire (where applicable) without problems
- [ ] VISCOM is working
- [ ] Radio communications are working for short and long range
- [ ] MCC and Zeus are correctly working
- [ ] There are no performance issues
- [ ] There are no game breaking error messages popping up on the screen and in the .rpt log

This is what I can think of from top of my head. If you have some more, please just edit and add to the list. 

For this testing, most of the stuff like gear loaded for soldiers were not touched so we can just skim through that lightly, pick few classes on random and check them for problems that could have come with mod set upgrade. Also, whoever has the time is welcome to test this and let me know of any problems in here. I will update the checklist accordingly. 

Thanks!

**Comment by milivojm** [comment]
I've written a wiki entry for setting up your dedicated server [here](https://github.com/CntoDev/cnto-mmt-repo/wiki/How-to-setup-your-own-dedicated-server-in-5-minutes).

**Comment by freghar** [comment]
I've added unit respawn to the checklist. Unfortunately, some of the bigger mods are taking too much time to download and I need to go do some other things, so my server won't be up until late afternoon.
However when it is up, we can at least test how the new mods behave on a linux-based server, even if it's not representative of what we'll use "in production".

**Comment by CNTODachi** [comment]
Hey Guys conducted testing this morning on our server here are the results.

1. The template would not load gave no entry 'bin\config.bin/CfgWeapon.tf47_at4_HEDP'. I then went into "f_AssignGear_Nato" and took out this entry and it gave me save error for "m3maaws_Heat" so took all tf47 entries out of the "f_AssignGear_Nato" and the template successfully loaded with no errors reported on screen.

To solve problem I unpacked the TF47 PBO and went on a search to see if the class ID's had changed but only change I could find was for the m3maaws optic, later I also exported from arsenal to confirm and everything was the same as in "f_AssignGear_Nato" I even copied and paste from exported arsenal just in case I missed something to no avail.

2. Once Loaded in I test drove all vehicles including Helicopters and tried all positions, tested firing on all and also while turned in and out on all. No Problems.

3. In game re-spawn as well as JIP worked fine. All good.

4. Tried out multiple functions in both Zeus and MCC all seemed to be in good order. Spawned in via Zeus all available factions, some factions were missing and also spawning "civilian other" causes an Arma 3 game crash for myself every time. 

Zeus Factions listed below:

Blufor: FIA / NATO / RHS USA
Opfor: ChDKZ / CSAT / RHS Russian / SLA
Indep: AAF / Afghan Militia / Eastern Militia / NAPA / RACS / Ultranationalists
Civilian: Chernarus Civs / Civs / Takistan Civs

Civilian other: BOSS / BOSS Transparent (Causes Game Crash every time) can we exclude from repo?

MCC Factions listed but do not spawn anything:

Other interactive / UN / CDF / Afghan police & Army / Iraqi Army / Novorussian / PMC / ISTS

5. I also took the time to try out the new weapons AR15's etc and had no issues apart from some weapon jams but one to watch out for in new ACE update :)

6. I also had no major performance issues.

7. My Acre seemed to be working fine but was on alone so couldn't test properly and same with VISCOM.

Hope this helps in some way guys, also I am putting the server back to it's original setting as I type.

Regards,
Dachi

**Comment by Abuk007** [comment]
Those listed factions are part of LOP. 
Do they not spawn with MCC only or is that also true for Zeus/Editor?
If its MCC only then its cross-mod compatibility.

Which mod is BOSS civilian faction part of?

Are TF47 launchers working correctly (despite errors)? (MAT team)

**Comment by CNTODachi** [comment]
The factions listed under **MCC Factions listed but do not spawn anything:** are listed in MCC but don't spawn in MCC and are not listed at all in Zeus therefore no option to spawn at all. 

Did not test if I could place in Editor.

They work in SP/Multi local tests via arsenal but on server they had to be stripped from AT and MAT soldiers in order to launch the Template on the server didn't test arsenal on server

**Comment by milivojm** [comment]
Hmm, guys I think you need to double check the modlist on the server 'cos I get no MAT error with latest RHS (official website via torrent).

**Comment by Abuk007** [comment]
I'll reupload RHS with original 4.0.1 files (was uploading a version updated by automatic-updater) in next 2 days (file sizes are huge) to be sure. Until then please test on localy hosted dedicated servers.

**Comment by Abuk007** [comment]
Game server RHS files have been reuploaded, please confirm if the issue persists. (Dachi, I and Ryujin can set server to new mods whenever testing is possible).

**Comment by CNTODachi** [comment]
I will retest as soon as I am able. Highway I also downloaded RHS from torrent.

I will check all mods in the new mod set are the ones linked in the mods list document otherwise I have no idea why LOP and TF47 would give us issues.

**Comment by Abuk007** [comment]
`@cba_a3_new;@ffcamopack_new;@hlcmods_new;@mbg_killhouses_a3;@pe_asrai_new;@mcc_sandbox_a3;@melb_new;@rh_acc;@rhs_afrf3_new;@rhs_usf3_new;@st_mods;@tao_foldmap_a3;@tf47_launchers_new;@rds;@rds_rhs_comp;@rickb_items;@swt_markers_a3;@lop_new;@lhd_atlas;@cup_terrains;@fallujah;@fata;@fdf_podagorsk;@panthera;@lingor_a3;@thirsk;@imrali_new;@prkz;@ares;@acre2_new;@ace_new;@cnto_stamina;`

Thats the mods in launch params of the server. 12 "_new" versions of mods. 

Apparently TF47 mod files were missing from the server, sorry for that. Should be good now.
LOP however is correctly uploaded.

**Comment by CNTODachi** [comment]
Haha that would explain the TF47 issues so happy days just the LOP issue to look at hopefully an easy fix will probably pop on the server on Sunday morning for testing again if anyone from MMT/R&D can help me out?

We test:

- [ ] LOP
- [ ] ACRE2
- [ ] VISCOM

**Comment by CNTODachi** [comment]
Link to [template](https://github.com/CntoDev/cnto-mmt-repo/blob/master/Mission%20Making%20Team/Missions/Templates/Official/Development/CNTO-r0b10-Coop_Template_v1.Altis.pbo?raw=true) with added ACE3 Module and compatible helicopter.

Also please see links for screenshots of testing conducted this morning on the CNTO Server.

MCC not showing any LOP factions in drop down list.

http://s14.postimg.org/izqeeaio1/LOP_MCC_Testing.png

Invisible LOP Factions.

http://s14.postimg.org/57bzinrwh/LOP_Testing.png

Regards,
Dachi

**Comment by Abuk007** [comment]
I'll re upload lop one final time. If this is still the case we ditch lop.

**Comment by TRyujin** [comment]
Be aware, LOP received an update to v1.8 last Thursday. Change log is:

> - Fix by Keeway

**Comment by CNTODachi** [comment]
Upload v8.1 as I also have this version already client side to see if this will fix. If not I Will do it later and test.

**Comment by Abuk007** [comment]
Roger. I will upload it later today. In the meanwhile please check if it
works local.

**Comment by CNTODachi** [comment]
I checked LOP 8.1 locally and all was fine.

I then uploaded this version to the server and tested on new template all is working fine the template is good to go. No LOP error on opening zeus either.

I took out the ACE3 Fast roping module as is was causing the template to throw me back into the mission selection lobby on the server. This will have to be investigated seperately.

@milivojm, @freghar, @TRyujin, @Abuk007, please confirm your happy with this and then we can release new template along with new mod set this weekend.

**Comment by freghar** [comment]
@CNTODachi Could you please push that version, unpacked, to the repository? I would fix #90 and #89 and push them as well, so we could test the final result on the CNTO server (both should be non-conflicting, but #89 needs >1 person to test).

**Comment by TRyujin** [comment]
> I took out the ACE3 Fast roping module as is was causing the template to throw me back into the mission selection lobby on the server. This will have to be investigated seperately.

Are we sure it's not because we have some fastroping script already in the template and it's causing the conflict?

**Comment by Abuk007** [comment]
If I understand correctly @CNTODachi 1.8.0 is on gameserver under @lop_new now?
Need to know so I upload the files now where neccessary.

**Comment by CNTODachi** [comment]
> @CNTODachi Could you please push that version, unpacked, to the repository? I would fix #90 and #89 and push them as well, so we could test the final result on the CNTO server (both should be non-conflicting, but #89 needs >1 person to test properly, works for just me).

Done

> Are we sure it's not because we have some fastroping script already in the template and it's causing the conflict?

No the script we voted to implement from Obi was never added to the template. No idea why it does not work I really need someone else with the new mod set to aid in testing to rule out mistakes in my client side mods.

> If I understand correctly @CNTODachi 1.8.0 is on gameserver under @lop_new now?
Need to know so I upload the files now where neccessary.

Yes it is I deleted LOP v1.7.2 as it was creating many issues that were also reported on the BI Forums.

**Comment by freghar** [comment]
> Done

Thanks, #89 fixed and pushed as a new .pbo.

**Comment by freghar** [comment]
@Abuk007 @TRyujin  The Mods google document mentions, for ACE3:

> ­ - Add ace_compat_rhs_usf3 / rhs_afrf3 / rh_acc.pbo

Where are these from?

**Comment by CNTODachi** [comment]
> @Abuk007 @TRyujin The Mods google document mentions, for ACE3:

- Add ace_compat_rhs_usf3 / rhs_afrf3 / rh_acc.pbo
Where are these from?

D:\Steam\steamapps\common\Arma 3\CNTO Test Repo\@ace\optionals

**Comment by freghar** [comment]
> Where are these from?

Right, thanks Dachi, found them under optional directory in the ACE repo.

**Comment by Abuk007** [comment]
Right, thats 1.8 dachi not 8.1 :) Anyways if you uploaded them to game server  then and there are no conflicts I will upload them overnight to VPS/Repo (please inform whoever declared to upload files, otherwise you might both end up uploading files in similar time creating conflicts and doubling work on simple task, one person is enough and we dont have 24h deadlines). Please give a final checkout from at least 2 people that we're green with that mod repo and template so we can push it on sunday.

**Comment by freghar** [comment]
I can't give the green light as the mods didn't work on my linux server, MELB - for some reason - refuses to export the vehicle classes, despite being loaded as mod.

**Comment by CNTODachi** [comment]
Myself and Freghar have completed testing on the server. Here is the link for the final template.

[CNTO-r0b10-Coop-Template](https://github.com/CntoDev/cnto-mmt-repo/tree/master/Mission%20Making%20Team/Missions/Templates/Official/!Stable/CNTO-r0b10-Coop-Template.Altis)

Viscom and Acre all good.

If Everyone is happy I will close down.

**Comment by TRyujin** [comment]
Please  clarify which mods have neen included and with which versions, also which additional pbos have been excluded or included. Update or at least comment on. The mods document on gdrive.

**Comment by freghar** [comment]
@TRyujin I used (for client side) exactly the mods and pbos specified by the Mods google document on R&D drive.

**Comment by CNTODachi** [comment]
> Please clarify which mods have neen included and with which versions, also which additional pbos have been excluded or included. Update or at least comment on. The mods document on gdrive.

Please when uploading documents to the shared GDrive make them editable so we can comment.

**Comment by TRyujin** [comment]
Cant access sharing permissions from the phone, i'll be able around evening.

**Comment by CNTODachi** [comment]
Rgr apart from LOP everything else was the same as on the MOD list including the:

Remove ace_markers / goggles / gforces / ai.pbo 
Add ace_compat_rhs_usf3 / rhs_afrf3 / rh_acc.pbo from optionals folder

**Comment by freghar** [comment]
> Please when uploading documents to the shared GDrive make them editable so we can comment.

Done, please see the R&D forum.

**Comment by Abuk007** [comment]
Roger. Pushing the repo update live.
