### ISSUE TITLE
Training Map Template - r0b10

### ISSUE THREAD

**Issue by Abuk007** [CntoDev/cnto-mmt-repo#91]
Please update the training map to r0B10.

**Comment by CNTODachi** [comment]
Ok I have uploaded my training grounds to the server all seems good was hoping this could be our new training map? Take a look see what you think.

**Comment by milivojm** [comment]
I'll have a look and take care of this. Can you point me to where the source files for this are?

Is this it? 

https://github.com/CntoDev/cnto-mmt-repo/tree/master/Mission%20Making%20Team/Missions/Templates/Official/Development/CNTO-r0b10-Training-Grounds.Altis

**Comment by CNTODachi** [comment]
Hey @milivojm that is where the files are being kept but after feedback from the guys playing a mini op on the server last night I have made some changes that have not been pushed to the GitHub yet once I have uploaded lastest version I will post here. Also I changed this mission over to the new Coop template r0b10 and it all worked great on the server so once uploaded and you have checked it over should be good for full deployment and moved into the stable area.

Regards,
Dachi

**Comment by milivojm** [comment]
It seems everything is working, can I close this issue?

**Comment by CNTODachi** [comment]
Yes mate if your happy I'm happy :) Training Template sorted we are "cooking on gas".
