### ISSUE TITLE
PvP Template - r0b10

### ISSUE THREAD

**Issue by Abuk007** [CntoDev/cnto-mmt-repo#92]
Please update the PvP template to match the COOP version.

**Comment by freghar** [comment]
don't forget to include the two commits from #87

**Comment by CNTODachi** [comment]
Rgr won't forget!

**Comment by CNTODachi** [comment]
So Guys the PvP template is complete and needs testing, also because I am not a GitHub Ninja do we accept Xanders pull request now or what is the next step?

**Comment by freghar** [comment]
@CNTODachi As his commits change the r0b9 template, just re-do his changes manually on top of r0b10. Not an ideal solution, but that's where we're stuck now.

https://github.com/CntoDev/cnto-mmt-repo/pull/87/commits/8da0732de5cc14a30b5dada921a36fa4227f64d5
https://github.com/CntoDev/cnto-mmt-repo/pull/87/commits/f3470b8a82300cf772333661da618b9fef211050

Or if @xand3rr can send a new pull request for the r0b10 PvP template, that could work out better.

**Comment by milivojm** [comment]
Yeah, I think the change made is easily made manually without polluting the commit line.

**Comment by CNTODachi** [comment]
Ok well it's done will move template to git. I made the changes manually on my original post just wasn't sure what to do here on Git.

Hopefully one of you guys can check and then it can be moved to stable.

I will mention the changes made in change description when uploading, I also added Independent faction onto the template and balenced their loadouts via F_Assign_Gear_AAF making them British.

**Comment by CNTODachi** [comment]
While Looking at the Template I came across this:

[AH Pilot Init](http://s17.postimg.org/6p0dijpm7/AH_Pilot_Init.jpg)

Should we have the highlighted green text ie. move into command I saw not point in it so want to know if there is a specific reason for it because if not I will remove from Template?

@Abuk007 @freghar @milivojm @TRyujin

**Comment by freghar** [comment]
@CNTODachi 
https://community.bistudio.com/wiki/moveInDriver

It is supposed to move the pilot into the helicopter. If you don't want that, you can safely remove it. However I don't think it's worth releasing a r0b11 for this alone.

**Comment by milivojm** [comment]
Just to reiterate my knowledge or lack of it, shouldn't there be an if around it? This is a playableUnit and code has sense only on player's machine (moveInDriver requires local arguments). I'm asking as not sure myself since this is init field.

```
if (local this) then {
    this moveInDriver VehNATO_Ah1;
};
```

**Comment by freghar** [comment]
@milivojm The vast majority of scripting commands simply don't do anything if they require a Local argument and the argument isn't local, without throwing an error. Therefore you don't need an explicit local check.

**Comment by CNTODachi** [comment]
@freghar I knew what the command was for, just didn't see a point to it really I will leave it for now but will make a note of it as it seems pointless, pilots should still spawn out of vehicles for Briefs in game.

The PvP template is coming along nicely hopefully have it finished and uploaded by tonight.

**Comment by CNTODachi** [comment]
It's up and ready for testing here [PvP Template](https://github.com/CntoDev/cnto-mmt-repo/tree/master/Mission%20Making%20Team/Missions/Templates/Official/Development/CNTO-r0b10-PvP-Template.Altis)

Regards,
Dachi

**Comment by CNTODachi** [comment]
BUMP BUMP anyone checked this out yet?

**Comment by Abuk007** [comment]
Will do some final testing today.

**Comment by Abuk007** [comment]
Training Grounds: Theres plenty of markers like: Empty (lat2_1), Empty (wp2) ... near AT Range and others. They are used in scripts spawning units and assigning them waypoints. Don't know if this is the most optimal way to do it. Possibly some scripts from \scripts\ranges\  could be replaced by in-game modules for both performance and clarity. That's not an issue but a thing to think about for future releases if thats possible, if not - dont worry about it.

Training looks good.

PvP: 

Independ**e**nt, not Independ**a**nt, thats for French :) Also INDIE have line:

> removeAllAssignedItems this;
in their init as the only faction.

Some things I've found lacking in some loadouts (which is probably a case from past):
f_assigngear:

UAV operators lack: UAV battery (ace item)
http://ace3mod.com/wiki/feature/logistics-uavbattery.html
(needs to be added by removing 2 mags and 1 granade to balance weight)

Mortar team doesnt have maptools - without them they can't perform their task.

Also please provide info about where to uncomment to re-assing night-time equipment.

**Comment by CNTODachi** [comment]
Ok the f_assignGear will have to be changed on all three templates I will make the updates then push it. I will also make the adjustments to all three factions.

Adding the uncomment stuff for night missions to the mission check list as kind of a How To guide.

**Comment by CNTODachi** [comment]
Additions have bee made to the Mission Checklist.
https://drive.google.com/open?id=1POsHAC3RufHNjTIIbSXIjfOHcEt8ZPrMhRzkCG297w8

Also I updated all of the f_assignGear for NATO/CSAT/AAF on all the templates.

I added the UAV Battery and took away 2 mags and 1 grenade.

I added the Maps tools to the Mortar Team Leader.

> Independent, not Independant, thats for French :) Also INDIE have line:

removeAllAssignedItems this;
in their init as the only faction.

Don't know where I have put **Independant** in the template could you tell me where? Also the **removeAllAssignedItems this;** was in from the last template and all the factions Squads have them in not just INDIE.

Also after you made the point about the UAV Operator I gave the FAC soldier a laser Des and 2 batteries making sure they all fit via the arsenal. Obviously I disabled these for the PvP giving all factions Bino's for no unfair advantage.

Regards,
Dachi

**Comment by CNTODachi** [comment]
Oh and don't worry about the FAC being over burdened he carries normal rifleman kit and some batteries so not heavy at all.

**Comment by CNTODachi** [comment]
Also I have added an acre module to the PvP template to turn off babel. Over direct.

**Comment by freghar** [comment]
@CNTODachi can we close this? is it working?

**Comment by CNTODachi** [comment]
Yeah it works.
